target_os = "android"
target_cpu = "arm64"
v8_target_cpu = "arm64"

is_official_build = true
is_debug = false
symbol_level = 0
enable_stripping = true
strip_binaries = true
is_component_build = false

target_sdk_version = "36"
min_sdk_version = "34"
android_archs = ["arm64-v8a"]

enable_reporting = false
enable_metrics = false
enable_dawn_tracing = false
chrome_enable_instrumentation = false
enable_locale = ["en-US"]

extra_chromium_flags = [
  "--enable-features=QuicTransport,ZstdContentEncoding,BrotliEncoding,"
  "OopRasterization,ZeroCopyRasterization,Prerender2,SimpleCache,"
  "CompactDiskCache,PartitionedAlloc,LowMemoryMode,PurgeMemoryOnBackground,"
  "V8CompilationCache,V8Liftoff,V8TurboFastCalls,WebAssemblyTieredCompilation,"
  "LiteModeDefault,ScriptStreaming,BackgroundTabThrottle,ReduceBackgroundNetwork,"
  "CleanSessionRestore,ReduceReferrerGranularity,ClientHintsDontSend,"
  "OptimizedHsts,AndroidSurfaces,AvifImageDecoding,WebpAlways,"
  "SlimOmnibox,MinimalToolbar,CacheCompression,LiquidGlassCompactUI",
  "--disable-features=BackForwardCache,HeavyAdPrivacyMitigations,"
  "NetworkServiceInProcess",
  "--disable-background-networking",
  "--disable-default-apps",
  "--disable-domain-reliability",
  "--disable-metrics",
  "--no-sandbox"
]
